# Eager execution
- https://www.tensorflow.org/guide/eager

TensorFlow's eager execution
- an imperative programming environment that evaluates operations immediately, without building graphs
- operations return concrete values instead of constructing a computational graph to run later

Eager execution: a flexible machine learning platform
-> Eager execution supports most TensorFlow operations and GPU acceleratio

In [3]:
import os
import tensorflow as tf
import cProfile

In [4]:
tf.executing_eagerly()

True

In [5]:
x = [[2.]]
m = tf.matmul(x, x)
m

<tf.Tensor: shape=(1, 1), dtype=float32, numpy=array([[4.]], dtype=float32)>

In [7]:
a = tf.constant([[1,2], [3,4]])
a

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [8]:
b = tf.add(a, 1)
print(b)

tf.Tensor(
[[2 3]
 [4 5]], shape=(2, 2), dtype=int32)


In [9]:
print(a * b)

tf.Tensor(
[[ 2  6]
 [12 20]], shape=(2, 2), dtype=int32)


In [10]:
import numpy as np

c = np.multiply(a, b)
print(c)

[[ 2  6]
 [12 20]]


In [11]:
print(a.numpy())

[[1 2]
 [3 4]]
